version: '3.8'

services:
  zookeeper_guardian:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper_guardian
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka_streamliner:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka_streamliner
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper_guardian
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_guardian:2181 # Nama service Zookeeper di atas
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_streamliner:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0